blender:
  asset_alembic: 1.ANIMA/{asset_type}/2.Publish/{asset}/4.Cache/{name}.v001.abc
  asset_publish: 1.ANIMA/{asset_type}/2.Publish/{asset}/{step}/{filename}.v001.{ext}
  asset_work: 1.ANIMA/{asset_type}/1.Work/{asset}/{step}/{filename}.v{version}.{ext}
  playblast: movies/playblast/Review/{sequence}/{shot}/{filename}_blast.v{version}.avi
  root_asset_publish: 1.ANIMA/{asset_type}/2.Publish/{asset}
  root_asset_work: 1.ANIMA/{asset_type}/1.Work/{asset}
  root_shot_publish: 1.ANIMA/{sequence}/2.Publish/{shot}
  root_shot_work: 1.ANIMA/{sequence}/1.Work/{shot}
  shot_alembic: 1.ANIMA/{sequence}/2.Publish/{shot}/4.Cache/{name}.v001.abc
  shot_publish: 1.ANIMA/{sequence}/2.Publish/{shot}/{step}/{filename}{step}.v001.{ext}
  shot_work: 1.ANIMA/{sequence}/1.Work/{shot}/{step}/{filename}{step}.v{version}.{ext}
maya:
  asset_alembic: cache/alembic/assets/{asset_type}/{asset}/{name}.v001.abc
  asset_publish: assets/{asset_type}/{asset}/{step}/{filename}.v001.{ext}
  asset_work: work/assets/{asset_type}/{asset}/{step}/{filename}.v{version}.{ext}
  playblast: movies/playblast/Review/{sequence}/{shot}/{filename}_Animation.v{version}.avi
  root_asset_publish: assets/{asset_type}/{asset}
  root_asset_work: work/assets/{asset_type}/{asset}
  root_shot_publish: scenes/{sequence}/{shot}
  root_shot_work: work/scenes/{sequence}/1.Work/{shot}
  shot_alembic: cache/alembic/scenes/{sequence}/{shot}/{type}/{name}.v001.abc
  shot_publish: scenes/{sequence}/{shot}/{step}/{filename}{step}.v001.{ext}
  shot_work: work/scenes/{sequence}/{shot}/{step}/{filename}{step}.v{version}.{ext}
