database: _database_
developer:
  name: MBLab Studio
  version: 2.0.0
engines:
- _id: ecef3256-8215-4c1e-998a-3a506d106882
  ext: blend
  name: Blender 3.6.2
  path: C:\Program Files\Blender Foundation\Blender 3.6\blender.exe
  publish: 5.BLENDER
  type: blender
  version: 3.6.2
  work: 5.BLENDER
- _id: 5afe240d-8198-4404-9f53-ba8543116ea2
  ext: ma
  name: Maya 2022
  path: C:/Program Files/Autodesk/Maya2022/bin/maya.exe
  publish: 9.MAYA
  type: maya
  version: '2022'
  work: 9.MAYA
- _id: 133d4edc-133b-406a-b9cc-603056759fa8
  ext: blend
  name: Blender 4.0.1
  path: C:/Program Files/Blender Foundation/Blender 4.0/blender.exe
  publish: 5.BLENDER
  type: blender
  version: 4.0.1
  work: 5.BLENDER
- _id: fdf1d36a-edd1-4232-94dd-36c0a2567eed
  ext: ma
  name: Maya 2023
  path: C:/Program Files/Autodesk/Maya2023/bin/maya.exe
  publish: 9.MAYA
  type: maya
  version: '2023'
  work: 9.MAYA
folder_production: 2.PROD/3.3D
project_root: L:/_JOBSATIVOS
relations:
  animation: 01_Animation
  assembly: 02_Assembly
  light: 03_Light
  lookdev: 2.LookDev
  model: 1.Model
  rigging: 3.Rig
setup_animation:
  camera:
    color:
    - 1
    - 0
    - 0
    group: CAM
    name: Camera
  character:
    color:
    - 0
    - 1
    - 0
    group: CHAR
    name: Character
  reference:
    children:
      character:
        color:
        - 0
        - 1
        - 0
        group: Char_ref
        name: Character
      environ:
        color:
        - 1
        - 1
        - 0
        group: Env_ref
        name: Environment
    color:
    - 0
    - 1
    - 1
    group: REFERENCE
    name: Reference
setup_light:
  camera:
    camera_name: turn_cam
    control: turn_loc
    name: Create Turn Camera
    range:
      in: 1
      out: 144
    target: LOOKDEV
    type: camera
  modeling:
    color:
    - 0
    - 1
    - 1
    group: LOOKDEV
    name: Import Model
    type: model
  studio_light:
    color:
    - 1
    - 1
    - 0
    group: SETUP_LIGHT
    name: Create Light Scene
    path: ''
    type: setup
  xgen:
    color:
    - 0
    - 1
    - 0
    group: XGN
    name: Create XGen group
    type: xgen
steps:
  asset:
  - 1.Model
  - 2.LookDev
  - 3.Rig
  shot:
  - 01_Animation
  - 02_Assembly
  - 03_Light
studio:
  name: Notan
types_assets:
- 1.Characters
- 2.Enviro
- 3.Props
